### ISSUE TITLE
"Awarded XP Per Player" is calculated incorrectly

### ISSUE THREAD

**Issue by givemeserotonin123** [mimic-fight-club/mimic-fight-club.github.io#62]
When creating an encounter, the area that shows "Awarded XP Per Player" does not show the correct amount of XP. As per page 489 of the Core Rulebook: "Note that if you adjust your XP budget to account for party size, the XP awards for the encounter don't change - you'll always award the amount of XP listed for a group of 4 characters".

The app shows the correct amount when the Party Size column is on 4, but if you adjust it from that it then calculates a different amount of XP. It should always show the XP based off of a Party Size of 4.

**Comment by Revictas** [comment]
I believe you are right!  I will look into this.  
Thanks for the feedback!

**Comment by Jupotter** [comment]
Hello

It seems that the change introduced a bug in the awarded experience calculation. Now, the awarded XP is always the sum of monster experience value. Instead, it should be the XP value for the equivalent encounter difficulty for a party size of 4.

For exemple, a party of 6 fighting a Severe encounter is currently awarded at least 180 XP (Severe threshold for 6), while they should be awarded always 120 XP.

Moreover, the awarded experience is not always at the threshold value, but can be different, as it is the sum of monster XP values. A Severe encounter for the group of 6 can thus award 200 XP.

**Comment by TheHeck** [comment]
> The awarded experience is not always at the threshold value, but can be different, as it is the sum of monster XP values.

This is by design. as per the [rules]( [the awarded experience is not always at the threshold value, but can be different, as it is the sum of monster XP values](https://2e.aonprd.com/Rules.aspx?ID=575)):
> the awarded experience is not always at the threshold value, but can be different, as it is the sum of monster XP values.

But yes it should be [scaled up or down to a group of four player](https://2e.aonprd.com/Rules.aspx?ID=578) if you have a different party size
> XP awards don’t change—always award the amount of XP listed for a group of four characters

Our group uses milestone XP. The XP awarded rules are split across the book making them hard to read... hence the confusion and why we made the change. Anyway it is reverted back to what it should be with #66
